stages:
  - test
  - deploy

run-php-units:
  only:
    - tags
  tags:
    - docker
  extends: .php-unit-tests


deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install curl -y
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://gitlab.adfinance.cz/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags

.php-unit-tests:
  stage: test
  image: gitlab.adfinance.cz:4567/docker/php8:php80-cli-composer
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor
  before_script:
    - pecl install xdebug && docker-php-ext-enable xdebug
  script:
    - composer install --optimize-autoloader --prefer-dist --no-progress
    - php -dxdebug.mode=coverage -dshort_open_tag=0 vendor/bin/phpunit --coverage-text --verbose --configuration phpunit.xml

